export const ACTION_TYPE = {
  GET_CLASSI: "GET_CLASSI",
  ON_ADD_URL: "ON_ADD_URL",
  ON_DELETE_URL: "ON_DELETE_URL",
  ON_DELETE_ERROR: "ON_DELETE_ERROR",
  ERROR_MESSAGE: "ERROR_MESSAGE",
  CLASSI_RECEIVED: "CLASSI_RECEIVED",
};
